//
// Created by arnaud on 12/12/23.
//

#ifndef CELLULAR_AUTOMATA_ARNAUD_CONSTANTS_H
#define CELLULAR_AUTOMATA_ARNAUD_CONSTANTS_H

#define NUMBEROFGENERATIONS 30
#define MAP_WIDTH 1024
#define MAP_HEIGHT 1024

#endif //CELLULAR_AUTOMATA_ARNAUD_CONSTANTS_H
