//
// Created by arnaud on 30/10/23.
//

#ifndef CELLULAR_AUTOMATA_ON_FIRE_FOREST_SIMULATION_CONSTANTS_H
#define CELLULAR_AUTOMATA_ON_FIRE_FOREST_SIMULATION_CONSTANTS_H

#define NUMBEROFGENERATIONS 20

extern int mapWidth;
extern int mapHeight;


#endif //CELLULAR_AUTOMATA_ON_FIRE_FOREST_SIMULATION_CONSTANTS_H

