//
// Created by arnaud on 30/10/23.
//

#ifndef CELLULAR_AUTOMATA_ON_FIRE_FOREST_SIMULATION_CONSTANTS_H
#define CELLULAR_AUTOMATA_ON_FIRE_FOREST_SIMULATION_CONSTANTS_H

#define NUMBEROFGENERATIONS 30
#define MAP_WIDTH 1024
#define MAP_HEIGHT 1024
#define THREAD_COUNT 4

#endif //CELLULAR_AUTOMATA_ON_FIRE_FOREST_SIMULATION_CONSTANTS_H

